version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    ports:
      - 52432:5432
    environment:
      TZ: "UTC"
      LANG: ja_JP.UTF-8
      POSTGRES_DB: sample_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
