version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    ports:
      - 52432:5432
    environment:
      TZ: "UTC"
      LANG: ja_JP.UTF-8
      POSTGRES_DB: sample_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: shitomo/kafka:2.8.1
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      # ホストマシンのプライベートIPを設定する
      KAFKA_ADVERTISED_HOST_NAME: 192.168.196.168
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
